version: "3"
services: 
  php7fpm:
    build: php7fpm
    container_name: php7fpm
    ports:
     - 9000:9000
    volumes: 
     - ./src:/var/www/html
    env_file:
      - .env
    links:
      - mariadb
      - "redis-session"
    networks: 
     - web-net
  nginx:
    build: nginx
    container_name: nginx
    volumes:
      - ./.docker/log/nginx:/var/log/nginx
      - ./src:/var/www/html
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    links:
      - php7fpm
    networks: 
     - web-net
  mariadb:
    image: mariadb:10.4
    container_name: "db-mariadb"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes: 
      - "./.docker/database:/var/lib/mysql"
    env_file:
      - .env
    networks: 
     - web-net
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin-csvitor"
    links:
        - mariadb
    ports:
        - 8080:80
    environment:
        - PMA_ARBITRARY=1
    networks: 
     - web-net

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - web-net
  mailhog:
    image: mailhog/mailhog
    container_name: "mailhog-csvitor"
    ports:
      - 1025:1025
      - 8025:8025
    networks: 
     - web-net
networks:
   web-net:
     driver: bridge
