#!/usr/bin/env bash
docker-compose up -d && \

printf "\e[34mCreated by Vitor Costa
links:
\e[32m
🌎 Web server: http://localhost/
⚙️ PHPMyAdmin: http://localhost:8080
✉️ Local emails: http://localhost:8025 \e[0m\n"

